/** Declaration file generated by dts-gen */

export function begin(options: any, onData: any, onEnd: any): any;

export function create(name: any, xmldec: any, doctype?: any, options?: any): any;

export function streamWriter(stream: any, options: any): any;

export function stringWriter(options: any): any;

export namespace begin {
    const prototype: {
    };

}

export namespace create {
    const prototype: {
    };

}

export namespace streamWriter {
    const prototype: {
    };

}

export namespace stringWriter {
    const prototype: {
    };

}

